name: Flutter Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout deploy branch
      run: |
        git checkout deploy
        git status

    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --base-href "/cat_mouse_tracker/"

    - name: Copy web build to docs folder
      run: cp -r build/web docs/
    
    - name: Deploy
      run: |
        git status
        git add --all
        git commit -m "update github pages"
        git push