name: Flutter Build and Deploy - Web

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: checkout deploy branch
        run: |
          git fetch --all
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --base-href "/cat_mouse_tracker/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/web

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
